# 베이스 이미지 설정
FROM eclipse-temurin:17

# JAR 파일 이름을 빌드 시 설정 가능하게 처리
ARG JAR_FILE=build/libs/*.jar

# Build-time ARG 정의
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG JWT_SECRET
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_S3_BUCKET
ARG REDIS_HOST
ARG REDIS_PORT
ARG KAKAO_CLIENT_ID
ARG KAKAO_REDIRECT_URI
ARG KAKAO_MESSAGE_TEMPLATE_ID
ARG KAKAO_CODE_REQUEST

# ARG를 런타임 ENV로 변환
ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV JWT_SECRET=$JWT_SECRET
ENV AWS_REGION=$AWS_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_S3_BUCKET=$AWS_S3_BUCKET
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV KAKAO_REDIRECT_URI=$KAKAO_REDIRECT_URI
ENV KAKAO_MESSAGE_TEMPLATE_ID=$KAKAO_MESSAGE_TEMPLATE_ID
ENV KAKAO_CODE_REQUEST=$KAKAO_CODE_REQUEST

# JAR 파일을 컨테이너 내부로 복사
COPY ${JAR_FILE} app.jar

# 컨테이너 실행 명령어 설정
CMD ["java","-jar","/app.jar"]