spring:
  datasource:
    url: ${COMMAND.DATABASE.URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${COMMAND.DATABASE.USERNAME}
    password: ${COMMAND.DATABASE.PASSWORD}

  data:
    mongodb:
      uri: ${QUERY.DATABASE.URI}

  application:
    name: ticketaka

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA.BOOTSTRAP.SERVERS} # Kafka 브로커 주소
    consumer:
      group-id: ${KAFKA.CONSUMER.GROUP.ID}       # Consumer 그룹 ID
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"        # 역직렬화할 패키지 설정
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: ${KAFKA.DEFAULT.TOPIC}      # 기본 Kafka 토픽 (옵션)

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  aws:
    credentials:
      accessKey: ${AWS.ACCESS.KEY.ID}
      secretKey: ${AWS.SECRET.ACCESS.KEY}
    s3:
      bucket: ${AWS.S3.BUCKET}
    region:
      static: ${AWS.REGION}
    stack:
      auto: false

jwt:
  secret: ${JWT.SECRET}

springdoc:
  swagger-ui:
    path: /api/swagger-ui
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: none
    tags-sorter: alpha

  api-docs:
    path: /api/v3/api-docs

  show-actuator: true

logging:
  level:
    '[ticketaka]': debug
    '[org.hibernate.type]': trace

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: "prometheus"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      enabled: true